defaults:
  - /encoder: dc_deep
  - /decoder: dc_deep
  - _self_

learning_rate: 0.00002
optimizer_config: ${oc.select:optimizer, null}  # Pass optimizer config to model, null if not specified

loss:
  _target_: autocast.models.autoencoder.AELoss
  losses:
    - _target_: torch.nn.MSELoss
  weights: [1.0]
