defaults:
  - data: reaction_diffusion
  - optional optimizer: null
  - optional nn/noise/input_noise_injector: null
  - model: encoder_processor_decoder
  - trainer: default
  - logging: wandb
  - _self_

seed: 42
experiment_name: epd
output:
  checkpoint_name: encoder_processor_decoder.ckpt
  save_config: true

eval:
  max_rollout_steps: 25

training:
  n_steps_input: auto
  n_steps_output: auto
  stride: auto
  rollout_stride: auto
  autoencoder_checkpoint: null
  freeze_autoencoder: false

hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
