defaults:
  - /backbone@backbone: vit_256
  - _self_

_target_: autocast.processors.diffusion.DiffusionProcessor
schedule:
  _target_: azula.noise.VPSchedule
denoiser_type: karras
n_steps_output: auto
n_channels_out: auto
sampler_steps: 20
sampler: euler
